name: OpenAPI Validation

on:
  push:
    paths:
      - docs/openapi.yaml
      - .github/workflows/openapi.yml
  pull_request:
    paths:
      - docs/openapi.yaml
      - .github/workflows/openapi.yml

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    name: Validate OpenAPI Specification

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate OpenAPI specification
        run: npm run docs:validate

      - name: Generate TypeScript client (test)
        run: npm run docs:generate typescript-axios

      - name: Upload generated client as artifact
        uses: actions/upload-artifact@v4
        with:
          name: typescript-client
          path: clients/typescript-axios/
          retention-days: 7

  swagger-ui-check:
    runs-on: ubuntu-latest
    name: Swagger UI Compatibility Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install swagger-ui-serve
        run: npm install -g swagger-ui-serve

      - name: Test Swagger UI serving
        run: |
          # Start swagger-ui-serve in background
          swagger-ui-serve docs/openapi.yaml &
          SERVER_PID=$!

          # Wait for server to start
          sleep 5

          # Check if server is responding
          curl -f http://localhost:8080 || exit 1

          # Kill the server
          kill $SERVER_PID

          echo "Swagger UI serving test passed"
